# Catch2
find_package(Catch2 CONFIG REQUIRED GLOBAL)

# GLAD
set(GLAD_PROFILE "core")
set(GLAD_ALL_EXTENSIONS ON)
find_package(glad CONFIG REQUIRED GLOBAL)

# GLM 
find_path(GLM_INCLUDE_DIRS glm/glm.hpp REQUIRED)
set(GLM_INCLUDE_DIRS ${GLM_INCLUDE_DIRS} PARENT_SCOPE)

# SDL2
find_package(SDL2 CONFIG REQUIRED GLOBAL)
